name: Tests IPA
on:
  push:
    branches:
      - main
jobs:
  tests-et-couverture:
    name: On test l'IPA
    runs-on: ubuntu-latest
    steps:
      - name: Préparation de Node.js
        uses: actions/setup-node@v1.4.4
        with:
          version: 17.x

      - name: Ouvrir la branche
        uses: actions/checkout@v2

      - name: Nétoyer les dépendances d'installation
        run: yarn install --frozen-lockfile

      - name: Vérifier les tests
        run: yarn couverture:tous

      - name: Envoyer couverure à Codecov
        uses: codecov/codecov-action@v2
